### ISSUE TITLE
Setup ESLint and wire it to the CI

### ISSUE THREAD

**Issue by danko-ui** [ITISHub/frontend#23]
We need to setup linter for our project and also run it for:

- push to `master` branch
- PR's to `master` branch

**Comment by ahmedsilat44** [comment]
@DanTrofimov Hey can I get assigned this issue. I'd like to do this

**Comment by ahmedsilat44** [comment]
I checked and Lint is already setup. Do u still want it to be written into the CI ?

**Comment by danko-ui** [comment]
Yep, but it didn't wired to the CI jobs .We still need to run ESlint on PRs to `master` branch and also do it during pushes after merge branches to `master`. 

 We need to modify our [`.github/workflows`](https://github.com/ITISHub/itishub-frontend/tree/master/.github/workflows), for example:

```yaml
name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
```

source - https://github.com/marketplace/actions/lint-action#javascript-example-eslint-and-prettier

@ahmedsilat44 fyi
